[versions]
compileSdk = "36"
minSdk = "28"

android-plugin = "8.11.1"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"

kotlinx-serialization-json = "1.9.0"

hilt-navigation = "1.2.0"
hilt = "2.57"

aboutlibraries = "12.2.4"

compose = "1.8.3"

core = "1.16.0"
core-splashscreen = "1.2.0-rc01"

appcompat = "1.7.1"

composeBom = "2025.07.00"
lifecycle = "2.9.2"
material = "1.3.2"
material-icons = '1.7.8'

navigation = "2.9.2"

ktor = "3.2.2"

m3color = "2025.4"

datastore = "1.1.7"

coil = "2.7.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }

appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material" }
compose-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive-android", version = "1.1.0" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "material-icons" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons" }

compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-client-websockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

m3color = { group = "com.github.Kyant0", name = "m3color", version.ref = "m3color" }

aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibraries" }

coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

[bundles]
core = [
    "core-ktx",
    "core-splashscreen",
    "appcompat"
]

compose = [
    "compose-runtime",
    "compose-runtime-livedata",
    "compose-foundation",
    "compose-ui",
    "compose-graphics",
    "compose-material3",
    "compose-adaptive",
    "compose-material-icons",
    "compose-material-icons-extended"
]

lifecycle = [
    "lifecycle-runtime-compose"
]

hilt = [
    "hilt-android",
    "hilt-navigation"
]

ktor = ["ktor-client-core", "ktor-client-okhttp", "ktor-client-logging", "ktor-client-auth", "ktor-client-websockets", "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json"]

[plugins]
android = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
